version: '3.9'
name: screensound
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: screensound-db
    environment:
      - POSTGRES_USER=murilo
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=screensound
    ports:
      - '5433:5433'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
