version: '3.9'
name: screensound
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: screensound-db
    environment:
      - POSTGRES_USER=murilo
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=screensound
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
