@WebApplication1_HostAddress = https://localhost:44337

POST {{WebApplication1_HostAddress}}/todoitems
Content-Type: application/json


{
  "name":"testandodnv",
  "isComplete":true
}

###

GET {{WebApplication1_HostAddress}}/todoitems

###

GET {{WebApplication1_HostAddress}}/todoitems/5

###


PUT {{WebApplication1_HostAddress}}/todoitems/5
Content-Type: application/json

{
  "name": "feed hahahahaha",
  "isComplete": false
}

###

DELETE {{WebApplication1_HostAddress}}/todoitems/2

###
