@WebApplication1_HostAddress = https://localhost:44337


GET {{WebApplication1_HostAddress}}/todos

###

POST {{WebApplication1_HostAddress}}/todos
Content-Type: application/json


{
  "name":"alou",
  "isComplete":true
}

###

GET {{WebApplication1_HostAddress}}/todos/4

###

PUT {{WebApplication1_HostAddress}}/todos/4
Content-Type: application/json

{
  "name": "feed hahahahaha",
  "isComplete": true
}

###

DELETE {{WebApplication1_HostAddress}}/todos/6

###

GET {{WebApplication1_HostAddress}}/todos/complete

###
